### PR TITLE
Add Government of Yukon

### PR DESCRIPTION
**Pull request by leeomara**
This pull request adds Government of Yukon as an issuer.

A submission via the Google form was also made by my colleague @ygdaverogers.

### CODE REVIEW

**Comment by deftdawg** [comment]
Someone representing the Yukon government (i.e with a @ yukon.ca email) must agree to [VCI Directory Agreement](https://github.com/the-commons-project/vci-directory/blob/main/VCI%20Directory%20Agreement.pdf) terms before VCI can add this issuer to the list of trusted issuers.

**Comment by leeomara** [comment]
Thanks for the info @deftdawg. What is the correct or acceptable way for someone representing the Yukon government to express agreement with the VCI Directory Agreement terms, so that the issue can be added?

**Comment by deftdawg** [comment]
@jdkizer9,  as the man who does the merging can you advise how parties go about agreeing to the terms? Do they send an email to a VCI address?  Is there some vetting that occurs?

I'm curious as I'm working on behalf of a different Canadian province to implement VCI, and will need to do this as well when the time comes.

**Comment by ygdaverogers** [comment]
@deftdawg I did submit the VCI Directory Issuer Request Form (https://docs.google.com/forms/d/e/1FAIpQLSe8rq9u_6vYNTvFZtGeOw6V2wv6UWax8hTnFYP5Awp7_VBzmQ/viewform) for Government of Yukon using my @yukon.ca email address on the afternoon of September 2nd. I agreed to the VCI Directory Agreement terms ("VCI Issuer SHC Attestation" on the form) at that time. I'm hoping that meets your needs.

**Comment by deftdawg** [comment]
Thanks @ygdaverogers, didn't realize you'd done that already.  In that case, I'd imagine you should be good to go, unless someone from VCI needs to contact you to confirm or vet or something.

**Comment by jdkizer9** [comment]
@ygdaverogers @leeomara Sorry about the delay on this. Merging now

**Comment by ygdaverogers** [comment]
Thanks @jdkizer9 and greetings from North of 60º. Enjoy your weekend everyone. Dave

**Pull request merged**
