### PR TITLE
Save directory snapshot

### PR DESCRIPTION
**Pull request by christianpaquin**
[Creating new PR, updated version of #207, to avoid fighting with github.]

This is an initial PR to extend the audit capability on directory, as prototyped [here](https://github.com/christianpaquin/vci-directory-auditor). Keeping it simple for an easier, scoped review.

This PR contains a script that downloads and persists the directory along with the issuer keys. Later, I'll create PRs to:
1. create a github action to run this daily
1. augment the auditing capabilities, by checking the issuer TLS config, and detecting duplications (kid, names, etc.), in the directory
1. compare with previous snapshots to see how the directory evolves

### CODE REVIEW

**Comment by christianpaquin** [comment]
The failing CI test is due to an [issuer](https://arrprd.metrohealth.net/fhir/api/epic/2021/Security/Open/EcKeys/32001/SHC/.well-known/jwks.json) not being available. Can this be overwritten or rerun?

**Comment by laurencebgood** [comment]
Is this going to be launched into this repo at some point? The README makes reference to the snapshots being live, but I'm not clear if that's a reference to @christianpaquin's repo or if the intention is to make it part of this one...

**Review by jdkizer9 — APPROVED** [review]
@christianpaquin sorry for the delay in this, bit looks good to me. I'm not super familiar with TS/JS projects, but do you think it makes sense for the compiled javascript to be a added to the `.gitignore` directory?

**Comment by christianpaquin** [comment]
> I'm not super familiar with TS/JS projects, but do you think it makes sense for the compiled javascript to be added to the `.gitignore` directory?

Yes, I'll add it to the ignore file.

**Comment by christianpaquin** [comment]
Ok, @jdkizer9, I updated the gitignore. Once that goes in, I'll have further PRs (in the new year, we all need a break :)) to add more functionality (including parsing CRLs that I [just added](https://github.com/christianpaquin/vci-directory-auditor/commit/5f026d7347e1fcba14a6c3062b9a1bf6d1851f5f) to my upstream project).

**Comment by jdkizer9** [comment]
@christianpaquin sounds good!

**Pull request merged**
