### PR TITLE
Update from SHC data

### PR DESCRIPTION
**Pull request by KreigD**
Update with website values from https://github.com/smart-health-cards/smart-health-cards.github.io/blob/gh-pages/_data/vci-issuers.json

### CODE REVIEW

**Comment by misterzero** [comment]
@KreigD please accept my PR to your fork with rebase to resolve conflicts. This repo changes every day, so please rebase early and often.

**Comment by KreigD** [comment]
> @KreigD please accept my PR to your fork with rebase to resolve conflicts. This repo changes every day, so please rebase early and often.

@misterzero I have accepted your PR. Is there anything else I need to do?

**Comment by misterzero** [comment]
> > @KreigD please accept my PR to your fork with rebase to resolve conflicts. This repo changes every day, so please rebase early and often.
> 
> @misterzero I have accepted your PR. Is there anything else I need to do?

That should do it, thanks!

**Comment by BenjaminatEpic** [comment]
@jdkizer9 @edwardjcruz Can you help me determine how we can quickly back out any changes from this PR to Epic organizations? This incorrectly overwrites the websites and naming conventions requested by Epic organizations. It doesn't appear to be revert-able and there is a downstream system responsible for copying these changes to the metadata file we would need to consider.

**Pull request merged**
