### PR TITLE
Update vci-issuers.json

### PR DESCRIPTION
**Pull request by miguelmal**
Add issuer for the government of puerto rico

### CODE REVIEW

**Comment by miguelmal** [comment]
hi, what are the next steps for the approval process? 

Regards,
Miguel Maldonado

**Comment by jpp9** [comment]
hi Miguel- thanks for this. we just need a representative of Puerto Rico public health or government to complete this [request form](https://docs.google.com/forms/d/e/1FAIpQLSe8rq9u_6vYNTvFZtGeOw6V2wv6UWax8hTnFYP5Awp7_VBzmQ/viewform) and attestation, and we can make the addition. let us know if you have any questions!

**Comment by miguelmal** [comment]
Hi, we have submitted the form.  Please advise on the next steps.

Regards,

Miguel

**Comment by jdkizer9** [comment]
@miguelmal I see that you requested a go-live date of 11/10/2021. Do you want to wait until that date or would you like to be added now?

**Comment by miguelmal** [comment]
Perfect the go-live date is fine.  Just making sure were all set.

Thank you,

Miguel

**Comment by miguelmal** [comment]
Hi, 
We’re still no recognized as a valid issuer. I did validate were already included in

https://raw.githubusercontent.com/the-commons-project/vci-directory/main/vci-issuers.json

Do need another step ?
Regards,

Miguel

**Pull request merged**
