### PR TITLE
Add British Columbia, Canada

### PR DESCRIPTION
**Pull request by dlh3**
Adding the ISS retrieved from decoding the BC Vaccination Card.

https://smarthealthcard.phsa.ca/v1/issuer/.well-known/jwks.json

### CODE REVIEW

**Comment by dlh3** [comment]
@BenjaminatEpic what is needed to get this PR accepted?

**Comment by BenjaminatEpic** [comment]
> e

@dlh3 we haven't been appending the .well-known/jwks.json is the main thing I can think of. If it's something other than that it'd be a question for James

**Comment by dlh3** [comment]
> @dlh3 we haven't been appending the .well-known/jwks.json is the main thing I can think of.

I didn't include that in the change.  I just dropped the full link in the PR comment for convenience.

Sorry @BenjaminatEpic, I thought I had seen you merging several other PRs.  My mistake, it looks like you were actually opening the PRs and @jdkizer9 was merging them.

**Comment by deftdawg** [comment]
@dlh3 an agent of the BC government must agree to the [VCI Directory Agreement](https://github.com/the-commons-project/vci-directory/blob/main/VCI%20Directory%20Agreement.pdf) terms before VCI can add BC's issuer to the list of trusted issuers.

**Comment by sjackman** [comment]
> Starting September 13, you need proof of vaccination to access some events, services and businesses. The easiest way to show proof is using the BC Vaccine Card. Get your card today. 

https://www2.gov.bc.ca/vaccinecard.html

Vaccine cards will be required in BC starting Monday September 13th. It'd be great to get this change merged in before then.

Ministry of Health
http://www.gov.bc.ca/health
https://www2.gov.bc.ca/gov/content/governments/organizational-structure/ministries-organizations/ministries/health/ministry-contacts
`hlth.health at gov.bc.ca`

Health Minister Adrian Dix
https://www.leg.bc.ca/learn-about-us/members/41st-Parliament/Dix-Adrian
https://en.wikipedia.org/wiki/Adrian_Dix
https://twitter.com/adriandix

I'm afraid I don't know his GitHub username to request a review of this PR. 😁

**Comment by deftdawg** [comment]
@sjackman someone from the BC government will need to fill out this form for agreeing to the terms: https://docs.google.com/forms/d/e/1FAIpQLSe8rq9u_6vYNTvFZtGeOw6V2wv6UWax8hTnFYP5Awp7_VBzmQ/viewform
Then the pull can be merged.

Ping the minister on twitter

**Comment by sjackman** [comment]
https://thecommonsproject.org/smart-health-card-verifier
https://apps.apple.com/ca/app/smart-health-card-verifier/id1572691390

@DanielBustoPHSA Hi, Daniel! This phone app `SMART Health Card Verifier` can be used to validate a Secure Health Card, like the BC Vaccine Card. This app currently displays the warning `Issuer not recognized` for BC Vaccine Cards, because the issuer https://smarthealthcard.phsa.ca/v1/issuer is not recognized, which this PR resolves.

image
image

Merging this PR requires the following form being submitted by someone at PHSA. Who would be the appropriate person at PHSA to do that?

https://github.com/the-commons-project/vci-directory/blob/main/VCI%20Directory%20Agreement.pdf
https://docs.google.com/forms/d/e/1FAIpQLSe8rq9u_6vYNTvFZtGeOw6V2wv6UWax8hTnFYP5Awp7_VBzmQ/viewform

**Comment by sjackman** [comment]
How To Check a BC Vaccine Card
https://www2.gov.bc.ca/assets/gov/covid-19/immunization/how_to_check_a_vaccine_card_poster_85_x_14.pdf

Proof of vaccination information for businesses
https://www2.gov.bc.ca/gov/content/covid-19/vaccine/proof/businesses

BC Vaccine Card Verifier App
https://apps.apple.com/ca/app/bc-vaccine-card-verifier/id1583114791
https://play.google.com/store/apps/details?id=ca.bc.gov.vaxcheck

British Columbia has their own vaccine card verifier app. I'd be curious to know what it does with a vaccine card from a non-BC issuer.

**Comment by deftdawg** [comment]
> British Columbia has their own vaccine card verifier app. I'd be curious to know what it does with a vaccine card from a non-BC issuer.

It tells you they are invalid documents...  Their app (android at least) embeds the BC public key within it and doesn't recognize any VCIs from the this projects issuers list.

Practically speaking, I would expect them to explicity trust a subset of issuers starting with neigbouring provinces and states...

**Comment by maxim-lab** [comment]
@BenjaminatEpic @dlh3 
Do you plan merge this change into Main Branch?

**Comment by BenjaminatEpic** [comment]
@maxim-lab As noted above, I don't have merge permissions in this repository. @edwardjcruz or @jdkizer9  would be the people to answer your question.

**Comment by briantkatch** [comment]
@edwardjcruz @jdkizer9 Just adding a +1 to merging B.C.'s issuer; as mentioned BC has been on CommonTrust for months and is now recognized in the SHC Verifier app, would be nice to have them listed here as some services are relying on this list to attach a name to an SHC issuer URL. Virtually everyone in BC is using an SHC from this issuer.

**Comment by ninosamson** [comment]
Hi folks - are we able to merge this PR? We noticed recently that the SHC Verifier App is no longer recognizing the BC issuer.

**Comment by sjackman** [comment]
This PR was resolved on 2022-12-06 by
- https://github.com/the-commons-project/vci-directory/pull/900

**Comment by edwardjcruz** [comment]
@sjackman thank you for adding this!

**Pull request closed without merging**
