### PR TITLE
fix Tampa General Hospital and University of South Florida

### PR DESCRIPTION
**Pull request by BenjaminatEpic**
Canonical endpoint changed to https://epicproxy.et0761.epichosted.com/FHIRProxy/api/epic/2021/Security/Open/EcKeys/32001/SHC

### CODE REVIEW

**Comment by BenjaminatEpic** [comment]
For the checks it's failing here - since we're trying to establish a new canonical iss could it be that it can't find the one that I'm adding since they're in the same PR? Or does the old endpoint have to be fully functional in order for the canonical_iss property to work? I can also try a PR with just the new endpoint if that makes more sense.

**Comment by edwardjcruz** [comment]
@BenjaminatEpic I believe the latter would be the case. From my understanding the test fail when the endpoints aren't functional - I agree a PR with just the new endpoint would make sense here. From the logs it seems that the old endpoint is unavailable causing the failure.

**Comment by BenjaminatEpic** [comment]
@edwardjcruz So we added the other endpoint but haven't been able to sync this and add the canonical endpoint. The 2 problems are: it's not recognizing the new canonical endpoint as existing in the directory, and it's still trying to test that the endpoint listed is correct. For this and future cases - do we need to maintain uptime on endpoints even when they are no longer canonical? Is this a testing artifact or something we are genuinely missing?

**Comment by BenjaminatEpic** [comment]
@edwardjcruz So we added the other endpoint but haven't been able to sync this and add the canonical endpoint. The 2 problems are: it's not recognizing the new canonical endpoint as existing in the directory, and it's still trying to test that the endpoint listed is correct. For this and future cases - do we need to maintain uptime on endpoints even when they are no longer canonical? Is this a testing artifact or something we are genuinely missing?

**Comment by edwardjcruz** [comment]
@jpp9 any ideas for how we can resolve this issue?

**Comment by jpp9** [comment]
@edwardjcruz @BenjaminatEpic for an ISS to be listed in this file, the keys should be hosted and functioning. if the hosting for the original `iss` is no longer provided or reliable, that `iss` should be removed and users should be informed they need to download new SHCs.

**Comment by BenjaminatEpic** [comment]
Thanks @jpp9, glad to hear we have a path forward on this. 
Can we look to move this commit forward or are there other steps that need to happen?

**Comment by BenjaminatEpic** [comment]
@edwardjcruz Do you know why we might be getting the "canonical_iss" not found in the directory error? The ISS it should be looking for is either right above or right below it

**Comment by edwardjcruz** [comment]
@BenjaminatEpic Apologies, our team is looking into the validation scripts. They should be behaving differently and picking up the canonical_iss that is in fact in the directory. Will keep you posted on this!

**Pull request merged**
